apiVersion: v1
kind: Pod
metadata:
 name: nginxpod
 labels:
  app: ngxinx
spec:
 containers:
 - name: nginxcontainer
   image: nginx
   ports:
   - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
 name: nginxsvc
 labels:
  app: ngins
spec:
 selector:
  app: nginx
 type: NodePort
 ports:
 - port: 80
   targetPort: 80
